    - name: Create Nginx vhost for {{ host }}
      template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ host }}

    - name: create symlink
      file:
        src: /etc/nginx/sites-available/{{ host }}
        dest: /etc/nginx/sites-enabled/{{ host }}
        state: link
        
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
